Spint3 step1
R0777/stellar-burgers pull request #5
Opened 2021-07-18 18:44 UTC by R0777

2021-07-19 19:24 UTC, AygulMalikova requested changes
Наша команда приносит извинения за долгое ожидание проверки. 
Хорошая работа! У вас структурированный код, разделенный на компоненты.

Но есть небольшие замечания. В первую очередь прошу вас обратить внимание на нереализованный функционал, который указан в задании. Пожалуйста, отформатируйте ваш код. И также, были оставлены другие комментарии и рекомендации по улучшению вашего кода.

Я напоминаю, что работа будет принята, как только все критические ошибки будут исправлены. Желаю вам удачи!

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/login/login.jsx
> +
Надо исправить:

Согласно заданию вам необходимо создать директорию pages. Внутри нее будут все страницы, которые описаны в задании и которые будут экспортироваться из одного файла index.js в директории pages

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/profile/profile.jsx
> +
Надо исправить:

В пункте **5. Получение и обновление информации о пользователе** задания указано, что у пользователя должна быть возможность обновить свои данные. На данный момент кнопки «Сохранить» и «Отмена» отсутствуют на вашей странице. Пожалуйста, добавьте кнопки и соответсвующий функционал

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/reset-pass/reset-pass.jsx
> +
Надо исправить:

1. По условиям задания неавторизованный пользователь не может напрямую попасть на маршрут /reset-password. На данный момент есть возможность попасть на эту страницу (набрав адрес в адресной строке).
2. После успешного восстановления пароля вам следует перенаправлять пользователя на главную страницу, т.к. пользователя нет никаких уведомлений о том, что запрос прошел успешно и может создаться впечатление, что функционал не работает.

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/routes/routes.jsx
> +        <IngredientPopup />
Надо исправить:

Если обновить страницу с ингредиентом, то шапка профиля пропадает. Пожалуйста, исправьте, чтобы разметка страница соответствовала макету

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/burger-constructor/burger-constructor.jsx
> +          <div className={styles.constructror__currency_btn} onClick={authCheck}><Button type="primary" size="large">Оформить заказ</Button></div>
Надо исправить:

В задании сказано, что при нажатии на кнопку «Оформить заказ» неавторизованный пользователь должен переадресовываться на маршрут /login. На данный момент этого редиректа не происходит

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/app-header/app-header.jsx
> +            <NavLink to="/profile" activeClassName={location.pathname === '/profile' && styles.active} className={styles.nav__list_item}>
Надо исправить:

Согласно заданию: панель навигации в шапке. Активной должна быть та ссылка на маршрут, где сейчас находится пользователь. Ссылка остаётся активной, если пользователь попадает на вложенные динамические маршруты.

Сейчас если пользователь находится на странице профиля, то ссылка в шапке неактивна.

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/app/app.jsx
>  import Modal from '../modal/modal'
Можно лучше:

Большая часть импортов не используется в данном файле. Пожалуйста, удалите их

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/app/app.jsx
>    const togglePopup = useSelector(state => state.order.togglePopup)
Можно лучше:

Эти 3 переменные не используются в вашем коде. Пожалуйста, удалите их, если в них нет необходимости

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/app/app.jsx
Надо исправить:

Обратите внимание, что код ниже дублируется с кодом внутри компонента Routes. Одинаковый код следует выносить и переиспользовать

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/app/app.jsx
> +<Router>
Надо исправить:

Очень важно иметь правильно отформатированный код для улучшения его читабельности. Пожалуйста, обратитесь к данной статье для изучения стандартов https://learn.javascript.ru/coding-style

Если вы используете IDE (например, VS code), то вы можете автоматически форматировать ваш код:
 https://stackoverflow.com/questions/29973357/how-do-you-format-code-in-visual-studio-code-vscode

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/account/account.jsx
> +const login = useSelector(store => store.loginUser.userData.name)
Можно лучше:

Вы можете достать необходимые значения из `store.loginUser.userData` и деструктуризовать полученный объект. Таким образом вам не придется дважды вызывать `useSelector`

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/account/account.jsx
> +// Register.propTypes = {
Можно лучше:

Закомментированные строки следует убирать, чтобы ваш код не терял читабельность

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/account-orders/account-orders.jsx
> +    <ul>
Надо исправить:

Данная разметка дублируется с компонентом OrdersList. Одинаковый код следует вынести и переиспользовать

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/burger-bun/burger-bun.jsx
> -    <li className={styles.bulka_item} onClick={getIngredients} >
Надо исправить:

Данная разметка дублируется в нескольких компонентах. Пожалуйста, вынести общий код

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/burger-main/burger-main.jsx
Надо исправить:

Как вы можете заметить, тип ингредиента дублируется в нескольких компонентах. Представьте, что в один момент необходимо будет добавить/удалить/изменить одно поле, и тогда это придется делать в нескольких местах. Это нарушает принцип DRY (про него можно почитать в этой статье https://habr.com/ru/post/144611/). Вам следует вынести в отдельный тип, разместить его внутри utils и импортировать внутри компонентов, где он используется.

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/burger-sauce/burger-sauce.jsx
> +  let location = useLocation()
Надо исправить:

Если значение переменной не перезаписывается напрямую, то следует использовать `const` вместо `let`

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/modal-switch/modal-switch.jsx
> +  let data = useSelector(state => state.api.data)
Надо исправить:

Если значение переменной не перезаписывается напрямую, то следует использовать `const` вместо `let`

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/modal-switch/modal-switch.jsx
> +  console.log(ingredient)
Можно лучше:

Перед отправкой работы, пожалуйста, убедитесь в том, что все строки кода содержащие debugger и console.log удалены.

2021-07-19 19:24 UTC, AygulMalikova commented on src/components/modal-switch/modal-switch.jsx
> +      <>
Надо исправить:

Данная разметка дублируется в компоненте IngredientPopup

2021-07-20 13:50 UTC, R0777 commented on src/components/reset-pass/reset-pass.jsx
> +
Не согласен с вами относительно 2ого пункта. Таких пользователей нужно отправлять на стр. /login . Почему?

2021-07-20 15:50 UTC, R0777 commented on src/components/app/app.jsx
>    const togglePopup = useSelector(state => state.order.togglePopup)
Не согласен. Как по вашему пользователь авторизуется если получил оба токена и основной еще не протух, а пользователь вышел со страницы, а потом туда зашел опять?

2021-07-20 16:27 UTC, R0777 commented on src/components/account/account.jsx
> +const login = useSelector(store => store.loginUser.userData.name)
Отличное замечание

2021-07-20 17:17 UTC, R0777 commented on src/components/burger-main/burger-main.jsx
А вот и нет.
Это отдельно взятые сущности (Булки, мясо и соусы.) и если я сделаю их общими и мне придется поменять что-то в конкретном ингредиенте, скажем показывать параметр злаковых, то он есть только в булках и придется разносить ваш общий код. Так что давайте не будем смотреть верстку которую до вас проверили 2 ревьюера.

2021-07-20 18:03 UTC, R0777 commented on src/components/modal-switch/modal-switch.jsx
> +      <>
Оставил вам выше несколько посланий. Посмотрите пожалуйста, буду признателен если вы их дополните своими комментариями

2021-07-20 19:56 UTC, AygulMalikova commented on src/components/aygul-list/aygul-list.jsx
> +const AygulList = () => {
Мне очень приятно, что вы назвали компоненты в честь моего имени 😁 
Но компонентам все же стоит соотвествующие наименования

2021-07-20 19:56 UTC, AygulMalikova commented on src/pages/forget-pass/forget-pass.jsx
Надо исправить:

На данный момент после нажатия на кнопку "Восстановить" на странице восстановления пароля происходит редирект на логин вместо reset-password страницы

2021-07-20 19:56 UTC, AygulMalikova commented on src/components/reset-pass/reset-pass.jsx
> +
Здесь я с вами согласна, второй комментарий снимается. Однако на данный момент после нажатия на кнопку "Восстановить" на странице восстановления пароля происходит редирект на логин вместо /reset-password страницы

2021-07-20 20:01 UTC, AygulMalikova requested changes
Очень хорошо! Вы исправили немало ошибок и движетесь в правильном направлении.

Осталось исправить совсем немного:
- добавить кнопку "отмена" на странице профиля
- исправить редирект со страницы /forgot-password на /reset-password
- переименовать компонент AygulList :) 

Желаю вам удачи!

2021-07-20 20:01 UTC, AygulMalikova commented on src/pages/account/account.jsx
> +</Button>
Отлично, что вы добавили кнопку сохранить. 

Надо исправить:
Однако кнопки "Отмена" все еще нет. Пожалуйста, добавьте ее

2021-07-21 23:33 UTC, R0777 commented on src/pages/account/account.jsx
> +</Button>
Все поправил, компонент переименовал. Но я решил, что если проект мой, то пусть в нем будет что-то и от вас...Так что теперь это наш общий авторский компонент. ;)

2021-07-22 09:29 UTC, AygulMalikova commented
Ваша работа принята, я вас поздравляю! Все ошибки исправлены и все условия задания выполнены. У вас отличный код, поделенный на компоненты. Так держать! Еще раз поздравляю и желаю вам дальнейших успехов!

P.S. к следующему спринту прошу все же переименовать компонент :)

2021-07-29 08:01 UTC, merged